# Generated by Django 3.1.2 on 2020-12-27 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20201228_0116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='profile_pic',
            field=models.ImageField(default='userimg.png', null=True, upload_to='customer_pic'),
        ),
    ]
